name: ic_tools
description: "ic_tools in the dart-language."
version: 1.0.93
homepage: https://github.com/levifeldman/ic_tools_dart


environment:
  sdk: ">=2.13.0 <3.0.0"
  # flutter: ">=1.20.0"

dependencies:
  http: ^0.13.3
  cbor: 4.0.2
  typed_data: ^1.3.0 
  archive: 3.1.2 # crc32 checksum functions
  base32: 2.0.0
  crypto: 3.0.1 
  ffi: ^1.1.2
  js: ^0.6.3
  tuple: ^2.0.0
  ed25519_edwards: ^0.3.1
